# -*- coding: utf-8 -*-
"""NN_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vGnFm8uHmbmo_FaHHBW_3EnsQP45o_9b
"""

import praw
import pandas as pd
import time

# Set up Reddit API credentials
reddit = praw.Reddit(
    client_id="JAPnA6i1mEMYV1NmR2scrA",
    client_secret="alkfqaq2r55nDM8cRKyDFU1wke1s8w",
    user_agent="script:dyslexia_research:v1.0 (by u/Radiant_Habit5662)"
)

# Target the dyslexia subreddit
subreddit = reddit.subreddit("Dyslexia")

# Create lists to store the data
posts_data = []

# Search for relevant keywords in post titles and content
keywords = ["problem", "struggle", "difficulty", "challenge", "communication",
            "talking", "conversation", "social", "anxiety", "nervous"]

# Get posts from different categories
for keyword in keywords:
    # Search in the subreddit
    for submission in subreddit.search(keyword, limit=100):
        # Avoid duplicates by checking if post ID is already in our data
        if not any(post['id'] == submission.id for post in posts_data):
            # Extract post data
            post_data = {
                'id': submission.id,
                'title': submission.title,
                'text': submission.selftext,
                'score': submission.score,
                'created_utc': time.strftime('%Y-%m-%d', time.localtime(submission.created_utc)),
                'num_comments': submission.num_comments,
                'url': f"https://www.reddit.com{submission.permalink}"
            }

            # Get comments
            submission.comments.replace_more(limit=0)  # Skip "load more comments" links
            comments = []
            for comment in submission.comments.list():
                if not comment.stickied:  # Skip stickied comments (usually from moderators)
                    comments.append({
                        'body': comment.body,
                        'score': comment.score
                    })

            post_data['comments'] = comments
            posts_data.append(post_data)

            # Be nice to Reddit's servers
            time.sleep(1)

# Convert to DataFrame for easier analysis
df = pd.DataFrame(posts_data)

# Save to CSV (without the comments column which is a list of dictionaries)
df.drop('comments', axis=1).to_csv('dyslexia_reddit_data.csv', index=False)

# Save full data including comments to JSON
import json
with open('dyslexia_reddit_data.json', 'w') as f:
    json.dump(posts_data, f)

print(f"Collected {len(posts_data)} unique posts about dyslexia challenges")
